// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snmbglpnyznagopoipbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNubWJnbHBueXpuYWdvcG9pcGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODE0NTcsImV4cCI6MjA2NTU1NzQ1N30.bYqxZewo8X6a8bxADFgt9dBv-TcJThItRiEQRApN1JY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);